import { Game, Player, Stat } from "./app.types";

export const defaultPlayer: Player = {
  id: 0,
  first_name: "John",
  last_name: "Doe",
  number: '0',
  team_id: 0,
  is_male: true,
  position: null,
  picture: null,
  home_town: null,
  social_medias: null,
  general_info: null,
  home_state: null,
  height: null,
  weight: null,
  age: null,
  sync_id: crypto.randomUUID()
};

export const defaultGame: Game = {
	id: 0,
	home_team_id: 0,
	away_team_id: 0,
	game_date: new Date().toJSON(),
	home_points_q1: 0,
	away_points_q1: 0,
	home_points_q2: 0,
	away_points_q2: 0,
	home_points_q3: 0,
	away_points_q3: 0,
	home_points_q4: 0,
	away_points_q4: 0,
	home_points_ot: 0,
	away_points_ot: 0,
	home_team_tol: 0,
	away_team_tol: 0,
	complete: false,
	clock: '00:00',
	home_final: 0,
	away_final: 0,
	period: 1,
	home_partial_tol: 0,
	away_partial_tol: 0,
	home_full_tol: 0,
	away_full_tol: 0,
	has_four_quarters: true,
	away_current_fouls: null,
	home_current_fouls: null,
	home_has_possession: null,
	game_link: null,
	event_id: null,
	season_id: 0,
	settings: null,
	stats: [],
	plays: [],
	sync_id: crypto.randomUUID()
};

export const defaultStat: Stat = {
  game_id: '',
  player_id: 0,
  minutes: 0,
  assists: 0,
  rebounds: 0,
  defensive_rebounds: 0,
  offensive_rebounds: 0,
  field_goals_made: 0,
  field_goals_attempted: 0,
  blocks: 0,
  steals: 0,
  threes_made: 0,
  threes_attempted: 0,
  free_throws_made: 0,
  free_throws_attempted: 0,
  points: 0,
  turnovers: 0,
  fouls: 0,
  plus_or_minus: 0,
  eff: 0,
  technical_fouls: 0,
  on_court: false,
  player_hidden: false,
  player_number: null,
}
